name: Test Upgrade built-in Hive to 3.1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '1.8', '11' ]
        hadoop: [ 'hadoop-3.2' ]
    name: Build Spark with JDK ${{ matrix.java }} and ${{ matrix.hadoop }}

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Hive module
        run: |
          ./build/sbt "hive/test-only" -P${{ matrix.hadoop }} -Djava.version=${{ matrix.java }}
